services:
  - type: web
    name: n8n
    env: docker
    region: singapore # optional (defaults to oregon)
    plan: starter # optional (defaults to starter)
    branch: main # optional (defaults to master)
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      - key: PGHOST
        fromDatabase:
          name: n8n-database
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: n8n-database
          property: database
      - key: PGPORT
        fromDatabase:
          name: n8n-database
          property: port
      - key: PGUSER
        fromDatabase:
          name: n8n-database
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: n8n-database
          property: password
    disk:
      name: n8n-disk
      mountPath: /home/node/.n8n
      sizeGB: 1

databases:
  - name: n8n-database
    plan: free
